/**
 * Simple, warm English with a little everyday slang. Keep labels clear,
 * estimates tentative, and privacy and health information precise.
 */
export const APP_TAGLINE = "Made for Aivel.";
export const GREETINGS = {
  morning: "Morning",
  afternoon: "Hey",
  evening: "Evening",
} as const;
export const HOME = {
  question: "How are you feeling today?",
  quickLogHint: "A quick check-in is enough. No pressure.",
  logToday: "Check in",
  partnerCardTitle: "What Ammar can see",
  partnerCardBody: "Your call. Pick what to share.",
  noteTitle: "A little note for you",
};
export const CYCLE = {
  dayOfCycle: (day: number) => `Day ${day} of your cycle`,
  nextPeriodIn: (days: number) => {
    if (days > 1) return `Your period may start in about ${days} days`;
    if (days === 1) return "Your period may start tomorrow";
    if (days === 0) return "Your period may start today";
    return `About ${Math.abs(days)} days past the estimate`;
  },
  basedOn: (count: number) =>
    count > 0
      ? ` Based on your last ${count} ${count === 1 ? "cycle" : "cycles"}.`
      : " Log another period to help fine-tune this.",
  openCalendar: "Open calendar",
  estimateBadge: "Estimate",
  addPeriod: "Log period",
  editPeriod: "Edit period",
  removePeriod: "Delete",
  savePeriod: "Save",
  stillGoing: "Leave blank if it is still going.",
  estimatesTitle: "This cycle, roughly",
  nextPeriodLabel: "Next period",
  fertileLabel: "Fertile window",
};
export const LOG = {
  title: "Today",
  moodLegend: "What's the mood?",
  symptomLegend: "How's your body feeling?",
  painLegend: "Pain level",
  flowLegend: "Flow",
  energyLegend: "Energy",
  sleepDuration: "Hours of sleep",
  sleepQuality: "How did you sleep?",
  waterLegend: "Water",
  activityLegend: "What have you been up to?",
  notesLabel: "Your notes",
  notesPlaceholder: "Anything you want to remember about today.",
  notesPrivate: "Only shared with Ammar if you turn on note sharing.",
  saved: "All saved. Thanks for checking in.",
  saveButton: "Save check-in",
  status: {
    "not-logged": "Not logged yet",
    partial: "Partly logged",
    complete: "All logged",
  },
  quickActions: {
    mood: "Mood",
    symptoms: "Symptoms",
    flow: "Flow",
    pain: "Pain",
    sleep: "Sleep",
    notes: "Notes",
  },
};
export const CALENDAR = {
  title: "Calendar",
  periodRow: "Period",
  periodRecorded: (range: string) => `Logged ${range}`,
  periodNotRecorded: "Not logged yet",
  logRow: "Daily check-in",
  logRecorded: "Logged",
  logMissing: "No check-in yet",
  addLog: "Add check-in",
  editLog: "Edit check-in",
  legend: {
    period: "Period",
    predicted: "Estimated period",
    fertile: "Fertile window",
    ovulation: "Estimated ovulation",
    logged: "Check-in logged",
  },
};
export const INSIGHTS = {
  title: "Insights",
  avgCycle: "Average cycle",
  avgPeriod: "Average period",
  variability: "Variation",
  steady: "Steady",
  avgPain: "Average pain",
  predictedTitle: "Next period estimate",
  noticeTitle: "What your check-ins show",
  historyTitle: "Period history",
  days: (count: number) => `${count} days`,
};
export const PARTNER = {
  homeTitle: "Aivel's day",
  keptPrivate: "Kept private",
  privatePlaceholder: "Aivel has kept this to herself.",
  sharedWithYou: "Shared with you",
  cyclePhase: "Cycle phase",
  nextPeriod: "Estimated period",
  mood: "Mood",
  painLevel: "Pain level",
  onPeriodToday: "On her period",
  symptoms: "Symptoms",
  sharedNote: "Her shared note",
  careTitle: "Ways to show up",
  careSubtitle: "A few ideas, based on what Aivel shares.",
  requestsTitle: "From Aivel",
  noRequests: "Nothing here right now.",
  noRequestsBody: "If Aivel asks for something, it will show up here.",
  notesTitle: "Your notes to each other",
  noNotes: "No notes yet.",
  noNotesBody: "A little hello is a good start.",
  sendNote: "Send a note",
  notePlaceholder: "Hope today is being kind to you.",
  noteFeeling: "Add a little feeling",
  wroteByYou: "You wrote",
  wroteForYou: "For you",
  askedSomething: "She could use a little support",
};
export const SHARING = {
  title: "What Ammar sees",
  subtitle: "Health details start private. Share only what feels right.",
  connected: "Connected",
  pairedOn: (date: string) => `Connected since ${date}.`,
  disconnect: "Disconnect",
  inviteTitle: "Invite Ammar",
  inviteBody:
    "Make a code and send it to Ammar. It works once and expires in 24 hours. Your health details stay private until you share them.",
  createInvite: "Create code",
  newInvite: "Create a new code",
  copyCode: "Copy code",
  copied: "Copied",
  expires: (when: string) => `Expires ${when}`,
  notConnected: "Ammar is not connected yet.",
  notConnectedBody: "Send an invite whenever you're ready.",
  toggleNote:
    "Turn a setting off to remove it from Ammar's view. Your original check-ins stay in your own space.",
  visibleNow: "What Ammar can see right now",
  visibleNowBody: "This is the full shared view.",
  nothingShared: "Nothing shared right now.",
  historyTitle: "History",
  detailsLink: "View details and history",
};
export const SUPPORT = {
  title: "What do you need?",
  subtitle: "A quick heads-up for Ammar.",
  send: "Send",
  sent: "Sent. Ammar will see it here.",
  off: "Support requests are off. Turn them on above to send one.",
  customLabel: "What's on your mind?",
};
export const AUTH = {
  welcomeBack: "Hey, welcome back",
  welcomeBody: "Your space is right here.",
  signIn: "Sign in",
  email: "Email",
  password: "Password",
  forgot: "Forgot password?",
  resetTitle: "Reset password",
  resetBody: "We'll email you a link to choose a new password.",
  resetSend: "Send reset link",
  resetSent: "If this email is registered, a reset link is on its way.",
  backToSignIn: "Back to sign in",
  closedTitle: "Registration is closed",
  closedBody:
    "Aivé is just for the two existing accounts. Use the password reset option if you need help getting back in.",
};
export const ONBOARDING = {
  steps: ["You", "Your cycle", "Last period", "Reminders"] as const,
  step: (current: number, total: number) => `Step ${current} of ${total}`,
  nameTitle: "What should we call you?",
  nameBody: "This is the name you'll see on your home screen.",
  nameLabel: "Preferred name",
  birthLabel: "Date of birth",
  birthHint: "Optional. Never shared with Ammar.",
  cycleTitle: "What's your cycle usually like?",
  cycleBody: "A rough guess is fine. Aivé learns from your logs.",
  cycleLengthLabel: "Average cycle length",
  cycleLengthHint: "From the first day of one period to the next.",
  durationLabel: "Average period length",
  durationHint: "How many days it usually lasts.",
  lastPeriodTitle: "When did your last period start?",
  lastPeriodBody:
    "This gives your estimates a starting point. You can edit it later.",
  lastPeriodLabel: "Last period start date",
  remindersTitle: "Want a gentle nudge?",
  remindersBody: "Change these anytime and keep notifications discreet.",
  remindYes: "Sure, remind me",
  remindNo: "Not right now",
  back: "Back",
  next: "Next",
  finish: "All set",
  failed: "Couldn't save that. Check your connection and try again.",
};
export const SETTINGS = {
  title: "Settings",
  accountSection: "Your space",
  editProfile: "Edit profile",
  editProfileBody: "Your name and cycle settings",
  reminders: "Reminders",
  remindersBody: "A gentle nudge, on your terms",
  sharing: "What Ammar sees",
  sharingBody: "Choose what to share",
  privacySection: "Privacy and data",
  privacySettings: "Privacy settings",
  privacySettingsBody: "Private mode, notifications, and your data",
  exportData: "Download your data",
  exportDataBody: "Everything you've logged",
  privacyPolicy: "Privacy policy",
  signOut: "Sign out",
  profileTitle: "Profile",
  aboutYou: "About you",
  fullName: "Full name",
  preferredName: "Preferred name",
  preferredNameHint: "What Aivé calls you.",
  saveProfile: "Save profile",
  cycleSettings: "Cycle settings",
  cycleSettingsBody: "Used until you have enough cycle history.",
  saveCycle: "Save cycle settings",
  profileSaved: "Profile updated.",
  cycleSaved: "Cycle settings updated.",
  connection: "Connection",
  partnerNote:
    "Aivel chooses what to share and can change it anytime. She can also disconnect your shared view.",
};
export const PRIVACY_SETTINGS = {
  title: "Privacy",
  deviceSection: "On this device",
  privacyMode: "Private mode",
  privacyModeBody: "Blur cycle details on your home screen until you tap.",
  appLock: "Pause before opening",
  appLockBody: "Add an extra tap when you open Aivé on this device.",
  hideSensitive: "Hide notification details",
  hideSensitiveBody: "Keep notifications neutral, without symptoms or dates.",
  dataSection: "Your data",
  dataBody: "Always yours to manage.",
  exportButton: "Download your data",
  exported: "Downloaded to this device.",
  deleteData: "Delete all logs",
  deleteAccount: "Delete my account",
  deletedData: "All your logs have been deleted.",
  noTracking:
    "Aivé has no ads, tracking pixels, or third-party analytics. Your data is stored in your Firebase project.",
  confirmDeleteDataTitle: "Delete all logs?",
  confirmDeleteDataBody:
    "This permanently deletes your periods, check-ins, cycles, and reminders. Your profile stays, but Ammar's shared summary is removed. This cannot be undone.",
  confirmDeleteAccountTitle: "Delete your account?",
  confirmDeleteAccountBody:
    "This permanently deletes your data, profile, and sign-in access. This cannot be undone.",
  confirmRevokeTitle: "Disconnect from Ammar?",
  confirmRevokeBody:
    "His access to your shared data ends and the shared summary is deleted. You can invite him again later.",
};
export const REMINDERS = {
  title: "Reminders",
  allowTitle: "Allow notifications",
  allowBody: "Reminders appear on this device while Aivé is open.",
  blocked:
    "Notifications are blocked in your browser settings. You can still see your reminders here.",
  allowButton: "Allow notifications",
  allowed: "Notifications are on for this device.",
  yourReminders: "Your reminders",
  newReminder: "New",
  noReminders: "No reminders yet.",
  noRemindersBody: "Set one for check-ins, vitamins, or anything else.",
  save: "Save reminder",
  typeLegend: "Type",
  titleLabel: "Title",
  messageLabel: "Message",
  messageHint: "Hidden when the switch below is on.",
  timeLabel: "Time",
  daysLegend: "Days",
  daysHint: "Leave all days unchecked for a daily reminder.",
  privateLabel: "Hide this reminder's details",
  privateBody: "Show a neutral notification instead of the message above.",
  everyDay: (time: string) => `Every day at ${time}`,
  onDays: (days: string, time: string) => `${days} at ${time}`,
};
export const STATES = {
  loading: "One sec…",
  errorTitle: "Something went wrong",
  errorBody: "Check your connection and try again.",
  tryAgain: "Try again",
  cancel: "Cancel",
  close: "Close",
  noCycleTitle: "No cycle data yet.",
  noCycleBody: "Log your last period to see your estimates.",
  noInsightsTitle: "Still getting to know your cycle.",
  noInsightsBody:
    "Log a few periods and your patterns will start showing up here.",
  genericLoadError: "Couldn't load this right now.",
};
export const PAIR = {
  title: "Enter your code",
  body: "Ask Aivel for a code, then enter the six characters here.",
  codeLabel: "Code",
  connect: "Connect",
  connected: "Connected. One sec…",
  note: "Connecting doesn't share everything. Aivel chooses each detail and can change her mind anytime.",
  needAccount: "You'll need an account before connecting.",
  wrongRole: "This account tracks its own cycle and cannot join as a partner.",
};
